api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

homepage:
    pattern: /
    defaults: { _controller: BackendBundle:Default:index }

#Imports Bundles routing
BackendBundle:
    resource: "@BackendBundle/Resources/config/routing.yml"
    prefix:   /

CategoryBundle:
    resource: "@CategoryBundle/Resources/config/routing.yml"
    prefix:   /

EntryBundle:
    resource: "@EntryBundle/Resources/config/routing.yml"
    prefix:   /

UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
