UserBundle:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

homepage:
    pattern: /
    defaults: { _controller: EntryBundle:Default:index }

#Imports Bundles routing
EntryBundle:
    resource: "@EntryBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
