security:
    firewalls:
        secured:
            pattern:  ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                use_referer: true
                default_target_path: homepage
                always_use_default_target_path: true
            logout: ~
            remember_me:
                key: mybudget410
                lifetime: 3600

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    #role_hierarchy:
    #    ROLE_ADMIN:       ROLE_USER
    #    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    emi: { password: 24747a70468d645b6245ca2a852984dfefccfd8b, roles: [ 'ROLE_ADMIN' ] }