parameters:
#    backend.example.class: MyBudget\BackendBundle\Example

services:
    mybudget.twig.locale_extension:
        class: MyBudget\BackendBundle\Twig\LocaleExtension
        tags:
            - { name: twig.extension }
