<?php

namespace MyBudget\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TargetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TargetRepository extends EntityRepository
{
	/*
	 * getFromTo() method
	 * @desc Returns all the targets from $from to $to
	 * @params DateTime $from, DateTime $to
	 * @return array collection $targets
	 */
	public function getFromTo(\DateTime $from = null, \DateTime $to = null)
	{
		$q = $this->createQueryBuilder('t');
		$parameters = array();
		
		if (!is_null($from)) {
			$q->where('t.month >= :from');
			$parameters['from'] = $from;
		}

		if (!is_null($to) && !is_null($from)) {
			$q->andWhere('t.month <= :to');
			$parameters['to'] = $to;
		} elseif (!is_null($to) && is_null($from)) {
			$q->where('t.month <= :to');
			$parameters['to'] = $to;
		}

		$q->orderBy('t.month', 'ASC');
		$q->setParameters($parameters);

		$q = $q->getQuery();
            
        $targets = $q->getResult();

        return (count($targets))? $targets : null;
	}
}
